extends:
  - airbnb
  - plugin:react/recommended
  - prettier
  - prettier/react
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
globals:
  __DEBUG__: true
  __WEBPACK__: true
  __VERSION__: true
parserOptions:
   ecmaFeatures:
     # enable JSX support
      jsx: true
rules:
  # use only single quotes/backquotes for strings 
  quotes: ["error", "single"]
  # trailing commas are mandatory
  comma-dangle: ["error", "always"]
  # spaces inside non-empty objects between brackets & content
  object-curly-spacing: ["error", "always"] 
  # indentation made with spaces not tabs
  indent: ["error", 4]
  # lines are max. 100 signs long
  max-len: ["error", { "code": 100 }]  
  # a line ends with semicolon, period
  semi: ["error", "always"]
  # addon to 'semi', cares about spaces before and after semicolon usage
  semi-spacing: ["error", {"before": false, "after": true}]
  prefer-destructuring: ["warn"]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-use-before-define: ["error"]
  no-warning-comments: [
    "warn",
    {
      "terms": ["todo", "fixme", "xxx", "to do", "fix me"]
    }
  ]
  import/no-extraneous-dependencies: [
    "error",
    {
      "devDependencies": [
        "./buildConfig.js",
        "./gulpfile.js",
        "**/*.test.js",
        "**/*.spec.js",
        "ui-test/**/*",
        "test/**/*"
      ]
    }
  ]
  react/jsx-no-bind: ["warn"]
  react/forbid-prop-types: ["warn"]
  react/prefer-es6-class: ["warn"]
  react/prop-types: ["warn"]
  react/require-default-props: ["warn"]
  react/sort-comp: ["warn"]
  react/jsx-boolean-value: ["off"]
  # align closing react component bracket with opening bracket
  react/jsx-closing-bracket: [1, 'line-aligned']
